-- =============================================================================
-- Category V1 Phase 1 schema: Category taxonomy foundation
-- Package: maatify/category
-- =============================================================================
--
-- Scope:
--   - This file contains only Category and Category Translation tables plus
--     the package-owned triggers required for the Category self-parent rule.
--   - It does not define Category, Product, Pricing, Inventory, Media, or Host
--     tables and has no relationship to any Host-owned table.
--
-- Timestamp contract:
--   - created_at, updated_at, and deleted_at are managed by the Category
--     application and stored as UTC values.
--   - No DEFAULT CURRENT_TIMESTAMP or ON UPDATE CURRENT_TIMESTAMP is used.
--
-- Deletion contract:
--   - deleted_at IS NULL means the record is not soft deleted.
--   - deleted_at IS NOT NULL means the record is soft deleted.
--   - Normal runtime hard delete is not part of Category V1 operations.
--
-- Relationship contract:
--   - All foreign keys are internal to the Category foundation.
--   - Internal foreign keys use ON DELETE RESTRICT and ON UPDATE RESTRICT.
-- =============================================================================

CREATE TABLE `maa_category_categories`
(
    `id`            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Internal immutable category identity generated by the database',
    `parent_id`     BIGINT UNSIGNED NULL COMMENT 'Nullable internal parent category identity; NULL identifies a root category; no Host-table reference',
    `code`          VARCHAR(100) NOT NULL COMMENT 'Stable immutable category code; remains reserved after soft deletion',
    `status`        VARCHAR(20) NOT NULL DEFAULT 'active' COMMENT 'Administrative category status; allowed values are active or inactive',
    `display_order` INT NOT NULL DEFAULT 0 COMMENT 'Business-controlled order within the same parent scope; ties are resolved by id',
    `created_at`    DATETIME NOT NULL COMMENT 'UTC timestamp assigned by the Category application when the category is created',
    `updated_at`    DATETIME NOT NULL COMMENT 'UTC timestamp assigned by the Category application on mutation, soft delete, or restore',
    `deleted_at`    DATETIME NULL COMMENT 'UTC timestamp assigned by the Category application on soft delete; NULL means not deleted',

    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_maa_category_categories_code` (`code`),
    KEY `idx_maa_category_categories_parent_status_deleted_order` (`parent_id`, `status`, `deleted_at`, `display_order`, `id`),
    CONSTRAINT `chk_maa_category_categories_status` CHECK (`status` IN ('active', 'inactive')),
    CONSTRAINT `fk_maa_category_categories_parent` FOREIGN KEY (`parent_id`)
        REFERENCES `maa_category_categories` (`id`)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT
)
ENGINE = InnoDB
DEFAULT CHARSET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Category hierarchy foundation with stable codes and soft deletion';

CREATE TABLE `maa_category_category_translations`
(
    `id`            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Internal immutable category translation identity generated by the database',
    `category_id`   BIGINT UNSIGNED NOT NULL COMMENT 'Internal category identity owning this translation; no Host-table reference',
    `language_code` VARCHAR(16) NOT NULL COMMENT 'BCP-47 language code supplied and validated by the Host application',
    `name`          VARCHAR(255) NOT NULL COMMENT 'Translated category name for the specified language',
    `description`   TEXT NULL COMMENT 'Optional translated category description for the specified language',
    `created_at`    DATETIME NOT NULL COMMENT 'UTC timestamp assigned by the Category application when the translation is created',
    `updated_at`    DATETIME NOT NULL COMMENT 'UTC timestamp assigned by the Category application on translation mutation, soft delete, or restore',
    `deleted_at`    DATETIME NULL COMMENT 'UTC timestamp assigned by the Category application on soft delete; NULL means not deleted',

    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_maa_category_category_translations_identity` (`category_id`, `language_code`),
    CONSTRAINT `fk_maa_category_category_translations_category` FOREIGN KEY (`category_id`)
        REFERENCES `maa_category_categories` (`id`)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT
)
ENGINE = InnoDB
DEFAULT CHARSET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Localized category names and descriptions keyed by category and BCP-47 language code';

-- MySQL does not permit a CHECK expression to reference an AUTO_INCREMENT
-- column. These package-owned triggers preserve the parent_id <> id invariant
-- after INSERT identity allocation and on every Category UPDATE.
DELIMITER $$

CREATE TRIGGER `trg_maa_category_categories_parent_not_self_ai`
AFTER INSERT ON `maa_category_categories`
FOR EACH ROW
BEGIN
    IF NEW.`parent_id` IS NOT NULL AND NEW.`parent_id` = NEW.`id` THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Category parent_id cannot equal id';
    END IF;
END$$

CREATE TRIGGER `trg_maa_category_categories_parent_not_self_bu`
BEFORE UPDATE ON `maa_category_categories`
FOR EACH ROW
BEGIN
    IF NEW.`parent_id` IS NOT NULL AND NEW.`parent_id` = NEW.`id` THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Category parent_id cannot equal id';
    END IF;
END$$

DELIMITER ;
