-- =============================================================================
-- Category V1 Phase 1 schema: Category taxonomy foundation
-- Package: maatify/category
-- =============================================================================
--
-- Scope:
--   - This file contains only Category, Category Content, and Category Image
--     Assignment tables plus
--     the package-owned triggers required for the Category self-parent rule.
--   - It does not define Catalog, Product, Pricing, Inventory, Media, or Host
--     tables and has no relationship to any Host-owned table.
--
-- Timestamp contract:
--   - created_at, updated_at, and deleted_at are managed by the Category
--     application and stored as UTC values.
--   - No DEFAULT CURRENT_TIMESTAMP or ON UPDATE CURRENT_TIMESTAMP is used.
--
-- Deletion contract:
--   - deleted_at IS NULL means the record is not soft deleted.
--   - deleted_at IS NOT NULL means the record is soft deleted.
--   - Normal runtime hard delete is not part of Category V1 operations.
--
-- Relationship contract:
--   - All foreign keys are internal to the Category foundation.
--   - Internal foreign keys use ON DELETE RESTRICT and ON UPDATE RESTRICT.
--
-- Ordering contract:
--   - display_order is always a positive position within the nullable
--     parent_id scope.
--   - Category application creation assigns it through the shared
--     maatify/persistence Ordering API inside its transaction.
--
-- Content lifecycle contract:
--   - Category application commands own Content creation, content update, soft
--     deletion, and restoration.
--   - (category_id, language_code) is the immutable logical identity.
--
-- Image Assignment contract:
--   - Category owns the assignment relation to a host-provided Media Asset ID.
--   - language_code and platform are nullable scope dimensions; NULL is an
--     exact value, not a fallback request. Empty strings are invalid.
--   - The stable identity is (category_id, media_asset_id, language_code,
--     platform), including soft-deleted rows.
--   - ordering_scope is a generated composite scope consumed by the shared
--     maatify/persistence Ordering API; it includes Category identity because
--     ordering is independent per Category and exact language/platform scope.
-- =============================================================================

CREATE TABLE `maa_category_categories`
(
    `id`            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Internal immutable category identity generated by the database',
    `parent_id`     BIGINT UNSIGNED NULL COMMENT 'Nullable internal parent category identity; NULL identifies a root category; no Host-table reference',
    `code`          VARCHAR(100) NOT NULL COMMENT 'Stable immutable category code; remains reserved after soft deletion',
    `status`        VARCHAR(20) NOT NULL DEFAULT 'active' COMMENT 'Administrative category status; allowed values are active or inactive',
    `display_order` INT NOT NULL COMMENT 'Business-controlled positive order within the same parent scope; assigned by the Category application through maatify/persistence',
    `created_at`    DATETIME NOT NULL COMMENT 'UTC timestamp assigned by the Category application when the category is created',
    `updated_at`    DATETIME NOT NULL COMMENT 'UTC timestamp assigned by the Category application on mutation, soft delete, or restore',
    `deleted_at`    DATETIME NULL COMMENT 'UTC timestamp assigned by the Category application on soft delete; NULL means not deleted',

    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_maa_category_categories_code` (`code`),
    KEY `idx_maa_category_categories_parent_status_deleted_order` (`parent_id`, `status`, `deleted_at`, `display_order`, `id`),
    CONSTRAINT `chk_maa_category_categories_status` CHECK (`status` IN ('active', 'inactive')),
    CONSTRAINT `chk_maa_category_categories_display_order` CHECK (`display_order` > 0),
    CONSTRAINT `fk_maa_category_categories_parent` FOREIGN KEY (`parent_id`)
        REFERENCES `maa_category_categories` (`id`)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT
)
ENGINE = InnoDB
DEFAULT CHARSET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Category hierarchy foundation with stable codes and soft deletion';

CREATE TABLE `maa_category_category_contents`
(
    `id`                     BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Internal immutable Category Content identity generated by the database',
    `category_id`            BIGINT UNSIGNED NOT NULL COMMENT 'Internal category identity owning this Content; no Host-table reference',
    `language_code`          VARCHAR(16) NULL COMMENT 'Nullable language identity: NULL is unlocalized Content; non-NULL is localized Content; Host owns semantic language support and locale policy',
    `language_code_identity` VARCHAR(16) GENERATED ALWAYS AS (COALESCE(`language_code`, '')) STORED COMMENT 'Generated uniqueness key that maps the unlocalized NULL identity to one database value',
    `name`                   VARCHAR(255) NOT NULL COMMENT 'Category name for unlocalized or specified localized Content',
    `description`            TEXT NULL COMMENT 'Optional Category description for unlocalized or specified localized Content',
    `created_at`             DATETIME NOT NULL COMMENT 'UTC timestamp assigned by the Category application when the Content is created',
    `updated_at`             DATETIME NOT NULL COMMENT 'UTC timestamp assigned by the Category application on Content mutation, soft delete, or restore',
    `deleted_at`             DATETIME NULL COMMENT 'UTC timestamp assigned by the Category application on soft delete; NULL means not deleted',

    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_maa_category_category_contents_identity` (`category_id`, `language_code_identity`),
    CONSTRAINT `chk_maa_category_category_contents_language_code` CHECK (
        `language_code` IS NULL
        OR (CHAR_LENGTH(TRIM(`language_code`)) > 0 AND CHAR_LENGTH(`language_code`) <= 16)
    ),
    CONSTRAINT `fk_maa_category_category_contents_category` FOREIGN KEY (`category_id`)
        REFERENCES `maa_category_categories` (`id`)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT
)
ENGINE = InnoDB
DEFAULT CHARSET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Unlocalized and localized Category Content keyed by category and nullable language identity';

CREATE TABLE `maa_category_category_image_assignments`
(
    `id`                     BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Internal immutable Category Image Assignment identity generated by the database',
    `category_id`            BIGINT UNSIGNED NOT NULL COMMENT 'Internal Category identity owning this assignment; no Host-table reference',
    `media_asset_id`         BIGINT UNSIGNED NOT NULL COMMENT 'Host-provided external Media Asset identity; deliberately has no foreign key',
    `language_code`          VARCHAR(16) NULL COMMENT 'Nullable exact language scope; NULL is a distinct unlocalized scope; Host owns semantic language support',
    `platform`               VARCHAR(255) NULL COMMENT 'Nullable exact platform scope; NULL is a distinct all-platform scope; no hardcoded platform enum',
    `language_code_identity` VARCHAR(16) GENERATED ALWAYS AS (COALESCE(`language_code`, '')) STORED COMMENT 'Generated uniqueness key mapping NULL language to one database value',
    `platform_identity`      VARCHAR(255) GENERATED ALWAYS AS (COALESCE(`platform`, '')) STORED COMMENT 'Generated uniqueness key mapping NULL platform to one database value',
    `ordering_scope`         VARCHAR(512) GENERATED ALWAYS AS (
        CONCAT(
            'C', CAST(`category_id` AS CHAR), '|',
            CASE
                WHEN `language_code` IS NULL THEN 'N:'
                ELSE CONCAT('L', CHAR_LENGTH(`language_code`), ':', `language_code`)
            END,
            '|',
            CASE
                WHEN `platform` IS NULL THEN 'N:'
                ELSE CONCAT('L', CHAR_LENGTH(`platform`), ':', `platform`)
            END
        )
    ) STORED COMMENT 'Generated exact Category plus language/platform ordering scope for maatify/persistence',
    `display_order`          INT NOT NULL COMMENT 'Business-controlled positive order within the exact Category and scope; assigned by the Category application through maatify/persistence',
    `created_at`             DATETIME NOT NULL COMMENT 'UTC timestamp assigned by the Category application when the assignment is created',
    `updated_at`             DATETIME NOT NULL COMMENT 'UTC timestamp assigned by the Category application on ordering, soft delete, or restore',
    `deleted_at`             DATETIME NULL COMMENT 'UTC timestamp assigned by the Category application on soft delete; NULL means not deleted',

    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_maa_category_category_image_assignments_identity` (
        `category_id`, `media_asset_id`, `language_code_identity`, `platform_identity`
    ),
    KEY `idx_maa_category_category_image_assignments_ordering` (
        `ordering_scope`, `deleted_at`, `display_order`, `id`
    ),
    CONSTRAINT `chk_maa_category_category_image_assignments_media_asset_id` CHECK (`media_asset_id` > 0),
    CONSTRAINT `chk_maa_category_category_image_assignments_language_code` CHECK (
        `language_code` IS NULL
        OR (CHAR_LENGTH(TRIM(`language_code`)) > 0 AND CHAR_LENGTH(`language_code`) <= 16)
    ),
    CONSTRAINT `chk_maa_category_category_image_assignments_platform` CHECK (
        `platform` IS NULL
        OR (CHAR_LENGTH(TRIM(`platform`)) > 0 AND CHAR_LENGTH(`platform`) <= 255)
    ),
    CONSTRAINT `chk_maa_category_category_image_assignments_display_order` CHECK (`display_order` > 0),
    CONSTRAINT `fk_maa_category_category_image_assignments_category` FOREIGN KEY (`category_id`)
        REFERENCES `maa_category_categories` (`id`)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT
)
ENGINE = InnoDB
DEFAULT CHARSET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Category-owned exact-scope references to host Media Asset identities';

-- MySQL does not permit a CHECK expression to reference an AUTO_INCREMENT
-- column. These package-owned triggers preserve the parent_id <> id invariant
-- after INSERT identity allocation and on every Category UPDATE.
DELIMITER $$

CREATE TRIGGER `trg_maa_category_categories_parent_not_self_ai`
AFTER INSERT ON `maa_category_categories`
FOR EACH ROW
BEGIN
    IF NEW.`parent_id` IS NOT NULL AND NEW.`parent_id` = NEW.`id` THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Category parent_id cannot equal id';
    END IF;
END$$

CREATE TRIGGER `trg_maa_category_categories_parent_not_self_bu`
BEFORE UPDATE ON `maa_category_categories`
FOR EACH ROW
BEGIN
    IF NEW.`parent_id` IS NOT NULL AND NEW.`parent_id` = NEW.`id` THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Category parent_id cannot equal id';
    END IF;
END$$

DELIMITER ;
